---
- name: Prepare all nodes for KarlCam deployment
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common
  tags:
    - common
    - preparation

- name: Install K3s cluster
  hosts: k3s_cluster
  become: yes
  serial: "{{ ansible_play_batch | length }}"
  roles:
    - k3s
  tags:
    - k3s
    - cluster

# Cilium removed - using K3s default Flannel CNI instead

- name: Deploy KarlCam infrastructure services
  hosts: control_plane[0]
  become: yes
  tasks:
    - name: Create KarlCam namespace
      kubernetes.core.k8s:
        name: karlcam
        api_version: v1
        kind: Namespace
        state: present
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml


    # Prometheus monitoring removed - not needed for KarlCam fog detection

  tags:
    - karlcam
    - monitoring

- name: Validate deployment
  hosts: control_plane[0]
  become: yes
  tasks:
    - name: Check cluster status
      shell: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: cluster_status

    - name: Display cluster status
      debug:
        msg: "{{ cluster_status.stdout_lines }}"

    - name: Check Cilium connectivity
      shell: cilium connectivity test --single-node
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: cilium_test
      ignore_errors: yes

    - name: Display connectivity test results
      debug:
        msg: "{{ cilium_test.stdout_lines }}"
      when: cilium_test.stdout_lines is defined

  tags:
    - validation